[build]
builder = "nixpacks"
buildCommand = "bun install"

[deploy]
startCommand = "bun run src/index.ts"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
PORT = "3000"
CORS_ORIGIN = "*"
NODE_ENV = "production"
  